import type { Metadata } from 'next';
import { Header } from '../../shared/components/shared';
//import favicon from '../../../public/favicon.ico';

export const metadata: Metadata = {
  title: 'ЗКК | Главная',
  description: 'Generated by create next app',

  // icons: {
  //   icon: favicon.src,
  // },
};

export default function HomeLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <main className='min-h-screen'>
      <Header />
      {children}
      {modal}
    </main>
  );
}
